# Generated by Django 5.0.2 on 2024-03-02 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=30)),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('referencia', models.CharField(max_length=30, verbose_name='Referência')),
            ],
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginas.endereco', verbose_name='Endereço')),
            ],
        ),
    ]
